
<!-- START TABLE -->
<div class="simplebox grid740">
	<div class="titleh">
		<h3>Checkout List</h3>
		<div class="shortcuts-icons">
			
		</div>
	</div>
	<!-- Start Data Tables Initialisation code -->
	<script type="text/javascript" charset="utf-8">
								$(document).ready(function() {
								oTable = $('#example').dataTable({
										"bJQueryUI": true,
										"sPaginationType": "full_numbers"
									});
								} );
							</script>
	<!-- End Data Tables Initialisation code -->


	<table cellpadding="0" cellspacing="0" border="0"
		class="display data-table" id="example">

		<thead>
			<tr>
				<th>ID Checkout</th>
				<th>Event name</th>
				<th>User create</th>
				<th>Date</th>
				<th>View</th>
			</tr>
		</thead>

		<tbody>

			
<?php
if(is_array($this->Items)){
foreach ( $this->Items as $key => $val ) {

	?>
				
				<tr class="gradeA">
				<td><?php echo $val['id'];?></td>
				<td><?php echo $val['event_name'];?></td>
				<td class="center"><?php echo $val['user_name'];?></td>
				<td class="center"><?php echo $val['date'];?></td>
				<td class="center"><a href="<?php echo $this->baseUrl('/admin/admin-checkout/view?id='.$val['id']);?>"> View</a></td>
			</tr>
				
				
				
				<?php
}
}
?>
			


		</tbody>
	</table>




</div>
<!-- END TABLE -->



