<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 				<?php echo $this->headTitle()?>
                <?php echo $this->headMeta()?>
                 <!--[if IE 7]>	  <link rel="stylesheet" type="text/css" href="style/ie7-style.css" />	<![endif]-->
                <?php echo $this->headLink()?>
                <?php echo $this->headScript()?>
   
    

      <style>
#stats {
	display: block;
}
</style>

</head>
<body>




    <div class="loginform">
    	<div class="title"> WHOPAIDFOR </div>
        <div class="body">
       	  <form id="form1" name="form1" method="post" action="<?php echo $this->baseUrl('/admin/admin-user/logon');?>">
          	<label class="log-lab">Username</label>
            <input name="username" type="text" class="login-input-user" id="textfield" value="Admin"/>
          	<label class="log-lab">Password</label>
            <input name="password" type="password" class="login-input-pass" id="textfield" value=""/>
            <input type="submit" name="button" id="button" value="Login" class="button"/>
       	  </form>
        </div>
    </div>
    
    </div>
</body>
</html>