
<!-- START TABLE -->
<div class="simplebox grid740">
	<div class="titleh">
		<h3>User List</h3>
		<div class="shortcuts-icons">
			
		</div>
	</div>
	<!-- Start Data Tables Initialisation code -->
	<script type="text/javascript" charset="utf-8">
								$(document).ready(function() {
								oTable = $('#users').dataTable({
										"bJQueryUI": true,
										"sPaginationType": "full_numbers"
									});
								} );
							</script>
	<!-- End Data Tables Initialisation code -->


	<table cellpadding="0" cellspacing="0" border="0"
		class="display data-table" id="users">

		<thead>
			<tr>
				<th>ID User</th>
				<th>Name</th>
				<th>Email</th>
				<th>Created Date</th>
				<th></th>
			</tr>
		</thead>

		<tbody>

			
<?php
if(is_array($this->Items)){
foreach ( $this->Items as $key => $val ) {
	$id = $val ["id"];
	$name = $val ["name"];
	$createdate = $val ["created"];
	?>
				
				<tr class="gradeA">
				<td><?php echo $id;?></td>
				<td><?php echo $name;?></td>
				<td><?php echo $val['mail_address'];?></td>
				<td class="center"><?php echo $createdate;?></td>
				<td class="center">Edit</td>
			</tr>
				
				
				
				<?php
}
}
?>
			


		</tbody>
	</table>




</div>
<!-- END TABLE -->



